services:
  rallly:
    image: lukevella/rallly:latest
    container_name: nasypeasy-rallly
    ports:
      - "3000:3000"
    volumes:
      - rallly-data:/data
    environment:
      - DATABASE_URL=postgres://rallly:rallly@rallly-db/rallly?sslmode=disable
      - SECRET_PASSWORD=pleasechangethispassworditshouldbe32pluschars
      - NEXT_PUBLIC_BASE_URL=${PUBLIC_URL}
      - SUPPORT_EMAIL=admin@example.com
    depends_on:
      - rallly-db
    restart: unless-stopped

  rallly-db:
    image: docker.io/postgres:16-alpine
    container_name: nasypeasy-rallly-db
    environment:
      - POSTGRES_USER=rallly
      - POSTGRES_PASSWORD=rallly
      - POSTGRES_DB=rallly
    volumes:
      - rallly-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rallly-data:
  rallly-db-data: