services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: nasypeasy-vaultwarden
    ports:
      - "8081:80"
    volumes:
      - vaultwarden-data:/data
    restart: unless-stopped

volumes:
  vaultwarden-data: