services:
  speedtest-tracker:
    image: docker.io/henrywhitaker3/speedtest-tracker:latest
    container_name: nasypeasy-speedtest
    ports:
      - "8765:80"
    volumes:
      - speedtest-data:/config
    restart: unless-stopped

volumes:
  speedtest-data:
