services:
  homer:
    image: docker.io/b4bz/homer:latest
    container_name: nasypeasy-homer
    ports:
      - "8082:8080"
    volumes:
      - homer-assets:/www/assets
    restart: unless-stopped

volumes:
  homer-assets:
