services:
  stirling-pdf:
    image: docker.io/stirlingtools/stirling-pdf:latest
    container_name: nasypeasy-stirling-pdf
    ports:
      - "8085:8080"
    volumes:
      - stirling-data:/usr/share/tesseract-ocr/4.00/tessdata
      - stirling-config:/configs
    restart: unless-stopped

volumes:
  stirling-data:
  stirling-config:
